# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI for cypress tests with docker containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: 'npm'
          
      - name: Install cypress
        run: |
         npm install

      - name: Build image for containers
        run: |
          docker build . -t cypress-docker-parallelization

      - name: Run Cypress tests with logs
        run: |
          docker compose up --exit-code-from cypress 2>&1 | tee cypress.log   
      # - name: Start containers
      #   run: |
      #     docker compose up -d
      
      - name: Run tests
        run: |
         npx cypress run
      
      # - name: Generate report
      #   run: |
      #    npm run generate-report-per-browser
